// This file was generated by the Anchor IDL tool. Do not edit it manually.

export type TruepvpBackend = {
  "version": "0.1.0",
  "name": "truepvp_backend",
  "instructions": [
    {
      "name": "createGame",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": true },
        { "name": "player", "isMut": true, "isSigner": true },
        { "name": "treasury", "isMut": true, "isSigner": false, "docs": ["CHECK: Treasury account for fees"] },
        { "name": "systemProgram", "isMut": false, "isSigner": false }
      ],
      "args": [
        { "name": "wagerAmount", "type": "u64" },
        { "name": "gameType", "type": "u8" }
      ]
    },
    {
      "name": "joinGame",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "player", "isMut": true, "isSigner": true },
        { "name": "systemProgram", "isMut": false, "isSigner": false }
      ],
      "args": []
    },
    {
      "name": "play",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "player", "isSigner": true }
      ],
      "args": [
        { "name": "round", "type": "u8" },
        { "name": "choice", "type": "u8" }
      ]
    },
    {
      "name": "resolveGameGoldRush",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "playerOne", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "playerTwo", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "signer", "isSigner": true, "docs": ["CHECK: The instruction signer must be one of the players"] }
      ],
      "args": []
    },
    {
      "name": "reportWinnerAndResolve",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "playerOne", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "playerTwo", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "signer", "isSigner": true }
      ],
      "args": [{ "name": "winner", "type": "publicKey" }]
    }
  ],
  "accounts": [
    {
      "name": "GameState",
      "type": {
        "kind": "struct",
        "fields": [
          { "name": "gameType", "type": "u8" },
          { "name": "players", "type": { "array": ["publicKey", 2] } },
          { "name": "wagerAmount", "type": "u64" },
          { "name": "playerOneChoices", "type": { "array": ["u8", 5] } },
          { "name": "playerTwoChoices", "type": { "array": ["u8", 5] } },
          { "name": "roundNumbers", "type": { "array": ["u8", 5] } },
          { "name": "isOver", "type": "bool" },
          { "name": "winner", "type": "publicKey" }
        ]
      }
    }
  ],
  "errors": [
    { "code": 6000, "name": "PlayerCannotJoinOwnGame", "msg": "A player cannot join their own game." },
    { "code": 6001, "name": "GameAlreadyFull", "msg": "This game is already full." },
    { "code": 6002, "name": "InvalidRound", "msg": "Invalid round number." },
    { "code": 6003, "name": "InvalidChoice", "msg": "Invalid choice." },
    { "code": 6004, "name": "AlreadyPlayedRound", "msg": "You have already played this round." },
    { "code": 6005, "name": "DuplicateChoice", "msg": "You cannot use the same chip twice." },
    { "code": 6006, "name": "GameAlreadyOver", "msg": "The game is already over." },
    { "code": 6007, "name": "GameNotFinished", "msg": "The game is not finished yet." },
    { "code": 6008, "name": "WrongGameType", "msg": "Instruction is not valid for this game type." },
    { "code": 6009, "name": "InvalidWinner", "msg": "Winner must be one of the players." },
    { "code": 6010, "name": "Unauthorized", "msg": "The signer is not authorized to perform this action." },
    { "code": 6011, "name": "InvalidPlayer", "msg": "Invalid player account passed." },
    { "code": 6012, "name": "Overflow", "msg": "Arithmetic overflow." }
  ],
  "metadata": {
    "address": "3FW4SxQYGK7p2Cp5U422LmZdi3WbatBr9zWj4RGtmoXi"
  }
};

export const IDL: TruepvpBackend = {
  "version": "0.1.0",
  "name": "truepvp_backend",
  "instructions": [
    {
      "name": "createGame",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": true },
        { "name": "player", "isMut": true, "isSigner": true },
        { "name": "treasury", "isMut": true, "isSigner": false, "docs": ["CHECK: Treasury account for fees"] },
        { "name": "systemProgram", "isMut": false, "isSigner": false }
      ],
      "args": [
        { "name": "wagerAmount", "type": "u64" },
        { "name": "gameType", "type": "u8" }
      ]
    },
    {
      "name": "joinGame",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "player", "isMut": true, "isSigner": true },
        { "name": "systemProgram", "isMut": false, "isSigner": false }
      ],
      "args": []
    },
    {
      "name": "play",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "player", "isSigner": true }
      ],
      "args": [
        { "name": "round", "type": "u8" },
        { "name": "choice", "type": "u8" }
      ]
    },
    {
      "name": "resolveGameGoldRush",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "playerOne", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "playerTwo", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "signer", "isSigner": true, "docs": ["CHECK: The instruction signer must be one of the players"] }
      ],
      "args": []
    },
    {
      "name": "reportWinnerAndResolve",
      "accounts": [
        { "name": "game", "isMut": true, "isSigner": false },
        { "name": "playerOne", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "playerTwo", "isMut": true, "isSigner": false, "docs": ["CHECK: Safe because of constraint"] },
        { "name": "signer", "isSigner": true }
      ],
      "args": [{ "name": "winner", "type": "publicKey" }]
    }
  ],
  "accounts": [
    {
      "name": "GameState",
      "type": {
        "kind": "struct",
        "fields": [
          { "name": "gameType", "type": "u8" },
          { "name": "players", "type": { "array": ["publicKey", 2] } },
          { "name": "wagerAmount", "type": "u64" },
          { "name": "playerOneChoices", "type": { "array": ["u8", 5] } },
          { "name": "playerTwoChoices", "type": { "array": ["u8", 5] } },
          { "name": "roundNumbers", "type": { "array": ["u8", 5] } },
          { "name": "isOver", "type": "bool" },
          { "name": "winner", "type": "publicKey" }
        ]
      }
    }
  ],
  "errors": [
    { "code": 6000, "name": "PlayerCannotJoinOwnGame", "msg": "A player cannot join their own game." },
    { "code": 6001, "name": "GameAlreadyFull", "msg": "This game is already full." },
    { "code": 6002, "name": "InvalidRound", "msg": "Invalid round number." },
    { "code": 6003, "name": "InvalidChoice", "msg": "Invalid choice." },
    { "code": 6004, "name": "AlreadyPlayedRound", "msg": "You have already played this round." },
    { "code": 6005, "name": "DuplicateChoice", "msg": "You cannot use the same chip twice." },
    { "code": 6006, "name": "GameAlreadyOver", "msg": "The game is already over." },
    { "code": 6007, "name": "GameNotFinished", "msg": "The game is not finished yet." },
    { "code": 6008, "name": "WrongGameType", "msg": "Instruction is not valid for this game type." },
    { "code": 6009, "name": "InvalidWinner", "msg": "Winner must be one of the players." },
    { "code": 6010, "name": "Unauthorized", "msg": "The signer is not authorized to perform this action." },
    { "code": 6011, "name": "InvalidPlayer", "msg": "Invalid player account passed." },
    { "code": 6012, "name": "Overflow", "msg": "Arithmetic overflow." }
  ],
  "metadata": {
    "address": "3FW4SxQYGK7p2Cp5U422LmZdi3WbatBr9zWj4RGtmoXi"
  }
};
